config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  post 'booking/search'

  get 'booking/show'
  get 'booking/booking_info'

  devise_for :users

  root 'home#index'
  namespace :api , defaults: {format: 'json'}do
    namespace :v1 do
     get 'booking/search'
  end
  end

end

app/models/bedding_type.rb
# type of bedding in a room 
class BeddingType < ActiveRecord::Base
  has_many :room_types
end

app/models/booked_room.rb
# Storing Booking and room Details 1 booking can have many rooms booked and 1 room can
 # occupied by more than 2  Bookings by different people
 class BookedRoom < ActiveRecord::Base
  belongs_to :booking
  belongs_to :room
end

app/models/booking.rb
# Booking can befrom mobile or thru website
# Booking can be Advance or can be on the spot
# Entry is made when finally the person occupies the room
class Booking < ActiveRecord::Base
  STATUS =['Advance Booking','On the spot Booking']
  MODE=['Website','App','Mobile Website']
  belongs_to :user
  has_many :rooms, :through => :booked_rooms  # Edit :needs to be plural same as the has_many relationship   
  has_many :booked_rooms
  has_one :entry

  def self.getting_reserved_room_ids(date_from,date_to,room_type,all_rooms_ids)
    byebug
    date_in,date_out,room_type = date_from,date_to,room_type
    reserved_rooms =  (date_in.present? && date_out.present?) ? BookedRoom.where("room_id in (?)",all_rooms_ids) : []
    reserved_room_ids=[]
    reserved_rooms.each do |r|
      if  r.booking.date_in.to_date>= date_in.to_date && r.booking.date_out<=date_out.to_time.localtime
       reserved_room_ids << r.room.id
      end
    end
     return reserved_room_ids
  end
end

app/models/entry.rb
# Entry when finally the user arrives entry is made whose corressponding booking was already ma
# made or can be made on the spot
class Entry < ActiveRecord::Base
  belongs_to :booking
end

app/models/room.rb
# Room is of a particular type like a luxury suite with queen size bedding and other amenities
class Room < ActiveRecord::Base
  belongs_to :room_type
  has_many :bookings, :through => :booked_rooms  # Edit :needs to be plural same as the has_many relationship   
  has_many :booked_rooms
end 

app/models/room_amenity.rb
# Room Amenity includes cleaning service,or full time room service
class RoomAmenity < ActiveRecord::Base
  has_and_belongs_to_many :room_types
end

app/models/room_attraction.rb
# Attraction can be room is pool facing and has gym facility with it
class RoomAttraction < ActiveRecord::Base
  has_and_belongs_to_many :room_types
end

app/models/room_type.rb
# Contains description of room which includes bedding type ,room attractions and room amenities
class RoomType < ActiveRecord::Base
  has_many :rooms
  belongs_to :bedding_type
  has_and_belongs_to_many :room_attractions
  has_and_belongs_to_many :room_amenities

def room_type_with_bedding_type
    "#{description}: #{bedding_type.description}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
end

app/controllers/api/v1/booking_controller.rb
class Api::V1::BookingController < Api::ApiController
    respond_to :json

  def search
     byebug
     all_rooms_ids = params[:room_type].present? ? Room.where("room_type_id=?",params[:room_type]).pluck(:id) : Room.pluck(:id)
     reserved_room_ids = Booking.getting_reserved_room_ids(params[:date_in].to_s,params[:date_out].to_s,params[:room_type],all_rooms_ids)
     @unreserved_rooms_ids = all_rooms_ids - reserved_room_ids   
     render :json=>{:vacant_rooms=>@unreserved_rooms_ids}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
      if resource.bookings.present?
        booking_booking_info_path
      else
        root_path
      end
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def search
     all_rooms_ids = params[:room_type].present? ? Room.where("room_type_id=?",params[:room_type]).pluck(:id) : Room.pluck(:id)
     reserved_room_ids = Booking.getting_reserved_room_ids(params[:date_in],params[:date_out],params[:room_type],all_rooms_ids)
     @unreserved_rooms_ids = all_rooms_ids - reserved_room_ids
  end

  def booking_info
    @reservations = current_user.bookings
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_type_id, :name, :room_number, :floor, :status)
    end
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/v1/booking_helper.rb
module Api::V1::BookingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/booking/_unreserved_rooms.html.erb
<h1> Unreserved Rooms</h1>
<table>
<thead>
<th>
Room Name
</th>
<th>
Room Number
</th>
<th>
Booking
</th>
<thead>
<tbody>
<% @unreserved_rooms_ids.each do |ur| %>
   <%room=Room.find(ur)%>
   <tr>
   <td><%=room.name%></td>
   <td><%=room.room_number%>
   </td>
   <td>
     <%= link_to "Book Now", room_path(room)%>
   </td>
   </tr>
<% end %>
</tbody>
</table>

app/views/booking/booking_info.html.erb
<h1> Booking Information</h1>
<table>
<thead>
  <th>Date In</th>
  <th>Date Out </th>
  <th> Booked On </th>
</thead>
<tbody>
<%@reservations.each do |r|%>
 <tr>
 <td><%=r.date_in.strftime('%c')%></td>
 <td><%=r.date_out.strftime('%c')%></td>
 <td><%=r.created_at.strftime('%c')%></td>
 </tr>
<%end%>
</tbody>
</table>

app/views/booking/search.js.erb
<% if @unreserved_rooms_ids.any?%>
  $('#room_list').html("<%=escape_javascript(render 'unreserved_rooms',:unreserved_room_ids => @unreserved_room_ids )%>");
<% else %>
  $("#room_list").html("<h2>No rooms available </h2>")
<% end %>

app/views/booking/show.html.erb
<h1>Booking#show</h1>
<p>Find me in app/views/booking/show.html.erb</p>

app/views/home/index.html.erb
<div class="container">
  <h2>Room Booking Service</h2>
  <div class="well">
  <%= form_tag("/booking/search",remote: true) do %> 
    <%= text_field_tag :date_in,'',:placeholder=>"Date In", :class => "datepicker" %>
    <%= text_field_tag :date_out,'', :placeholder=>"Date Out",:class => "datepicker" %>
    <%=select_tag "room_type", options_from_collection_for_select( RoomType.all,:id,:room_type_with_bedding_type ), prompt: " Room Type"%>
 
    <%= submit_tag "Submit"%>
  <%end%>
  </div>
  <div id="room_list" class="well">
  <%if @unreserved_rooms_ids.present?%>
   <%=render :partial => "booking/unreserved_rooms", :locals => {:unreserved_rooms_ids => @unreserved_rooms_ids}%>
  <%end%>
</div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({startDate: '+0d',endDate: '+6m',format: 'dd/mm/yyyy'});
  });
</script>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_type_id %><br>
    <%= f.text_field :room_type_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :room_number %><br>
    <%= f.text_field :room_number %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room type</th>
      <th>Name</th>
      <th>Room number</th>
      <th>Floor</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_type %></td>
        <td><%= room.name %></td>
        <td><%= room.room_number %></td>
        <td><%= room.floor %></td>
        <td><%= room.status %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>